# fly.toml app configuration file generated for litefs-readme on 2023-04-30T11:00:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "litefs-readme"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true
  enable_consul = true

[env]
  PORT = "8081"
  PRIMARY_REGION = "sin"

[[mounts]]
  source = "litefs"
  destination = "/var/lib/litefs"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
